env:
  - name: PYTHON_VERSION
    value: "3.10.10"
  - name: PORT
    value: "5005"

services:
  - type: web
    name: rasa-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: rasa run --enable-api --cors "*" --port $PORT
    port: 5005  # Renderがアクセスできるポート番号を指定

