services:
  - type: web
    name: rasa-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "rasa run --enable-api --cors '*' --port $PORT"
    envVars:
      - key: CHANNEL_SECRET
        value: ${CHANNEL_SECRET}
      - key: CHANNEL_ACCESS_TOKEN
        value: ${CHANNEL_ACCESS_TOKEN}
      - key: FIREBASE_KEY
        value: ${FIREBASE_KEY}