env:
  - name: PORT
    value: "5005"  # Renderが使用するデフォルトポートを指定
  - name: PYTHON_VERSION
    value: "3.10.10"

services:
  - type: web
    name: rasa-server
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "rasa run --enable-api --cors '*' --port $PORT"
    envVars:
      - key: PORT
        value: "5005"

