env:
  - name: PYTHON_VERSION
    value: "3.10.10"

services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PORT
        value: "5000"  # 必要なポート番号を指定

